[package]
name = "to_do_list"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", features = [
    "persistence",
] }
egui = "0.27.2"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
